### ISSUE TITLE
Установка 2.0-alpha

### ISSUE THREAD

**Issue by dmpas** [oscript-library/ovm#13]
хочу выполнить
`ovm install alpha`
или
`ovm install 2.0` / `ovm intall 2.0.3` / `ovm install 2.0.3-alpha`

и потом через `ovm use stable` и `ovm use alpha` тестить совместимость поведения.

**Comment by nixel2007** [comment]
мечта-мечта. ovm пока скачивает только с сайта, а там их нет :(

**Comment by dmpas** [comment]
> мечта-мечта. ovm пока скачивает только с сайта, а там их нет :(

@nixel2007  я тут начал немного

https://github.com/oscript-library/ovm/pull/14

**Comment by sfaqer** [comment]
Реализовано в https://github.com/oscript-library/ovm/pull/22
