### ISSUE TITLE
Неправильная версия в параметрах приложения

### ISSUE THREAD

**Issue by igostv** [oscript-library/ovm#19]
https://github.com/oscript-library/ovm/blob/29c28091d88c1811af351036a9add8a18cb4c9b5/src/cmd/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F.os#L16

Текущая версия "1.0.0-RC17";

**Comment by nixel2007** [comment]
Да, спасибо. Вероятно, закрою этот вопрос вместе в переводом на осень

**Comment by sfaqer** [comment]
Исправлено в #20
