### ISSUE TITLE
Не устанавливается версия 2.0.0 на ovm 1.2.1 (ошибка 404 при скачивании)

### ISSUE THREAD

**Issue by pravets** [oscript-library/ovm#28]
При попытке установить версию 2.0.0, которая есть в списке доступных и должна по логике ставить версию 2.0.0 RC4 получаем ошибку.

Список доступных версий:
```shell
>ovm ls -a
1.0.10 -> unknown -> not installed -> https://oscript.io/downloads/archive/1_0_10
...
2.0.0 -> unknown -> not installed -> https://oscript.io/downloads/archive/2_0_0_rc4
```

Версия ovm:
```shell
$ ovm -v
1.2.1
```

Ошибка при установке:
```shell
> ovm install 2.0.0 
Установка OneScript 2.0.0...
Скачиваю установщик версии 2.0.0-x64...
Скачивание завершено
ОШИБКА - Ошибка скачивания установщика. Текст ответа: 
<!DOCTYPE html>
...
</body>
</html>
ОШИБКА - {Модуль oscript://core.Class.УстановщикOneScript / Ошибка в строке: 113 / {Модуль oscript://core.Class.УстановщикOneScript / Ошибка в строке: 190 / 404}}
```

**Comment by nixel2007** [comment]
Версии 2.0.0 не может быть в списке доступных, так как она ещё не выпущена :)
Вы выполняете ls без флага -r, то есть просто выводите то, что у вас уже установлено

**Comment by pravets** [comment]
![image](https://github.com/oscript-library/ovm/assets/24823089/3e7b96d7-57ee-48a7-8502-fce21651cffb)

выполнил с флагом -r
версия 2.0.0 в списке доступных все же есть
но суть понятна, буду использовать dev

**Comment by nixel2007** [comment]
preview должен скачать последний релиз кандидат версии 2.0
