### ISSUE TITLE
Удаление stable

### ISSUE THREAD

**Issue by 240596448** [oscript-library/ovm#7]
Поставил stable и 1.4.0 (сейчас последняя)
Используется 1.4.0

При удалении stable говорит, что версия используется.
Причина в проверке соответствия даты файлов https://github.com/oscript-library/ovm/blob/7933565d5a7f5e25238313db0c0249354c1955bf/src/core/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%92%D0%B5%D1%80%D1%81%D0%B8%D0%B8OneScript.os#L58-L60

Мне кажется это не корректно.

Можно же брать версию из линка. Например, из вывода консолей cmd/bash.
Или из ПолучитьТочнуюВерсиюOneScript()
 
![image](https://user-images.githubusercontent.com/35220983/97759473-2f307c00-1b12-11eb-8842-fd50210690e8.png)

PS: mklink /D выглядит более удобным в использовании (определении пути)

**Comment by 240596448** [comment]
Определение ТекущейВерсии из Симлинка #8

**Comment by nixel2007** [comment]
> Можно же брать версию из линка. Например, из вывода консолей cmd/bash.
Или из ПолучитьТочнуюВерсиюOneScript()

небольшое уточнение - ПолучитьТочнуюВерсиюOneScript возвращает именно версию оскрипта, через oscript --version. А имена каталогов - это "алиасы" в терминах овм. Но идея с dir/ls мне нравится!

**Comment by 240596448** [comment]
Реализовано https://github.com/oscript-library/ovm/pull/8
