### ISSUE TITLE
Смена поведения под NET.Core

### ISSUE THREAD

**Issue by aliczin** [oscript-library/ovm#9]
В связи https://github.com/EvilBeaver/OneScript/issues/1037

Будет меняться формат дистрибутива OScript. В связи с чем если OVM будет качать по 70 метров каждый раз с RUNTIME - это будет не кошерно.

С другое стороны сам OVM возможно перестанет работать, Возможно его стоит перенести в движок как отдельное C# приложение.

Одно точно - что-то менять придется. Пусть задачка висит как связанная, чтобы не забыть

**Comment by EvilBeaver** [comment]
nvm качает по 100 метров и вроде ничего )

А вообще да, можно поставлять FDD версию дистрибутива, как сейчас, но требовать наличия рантайма на машине

**Comment by asosnoviy** [comment]
@nixel2007 ты понял что  надо пометь в ovm? а то я плохо понимаю ~~китайский~~ английский =(

**Comment by nixel2007** [comment]
Хз, не понимаю, в чем проблема. Раньше был зип, потом тоже будет зип. Овм качает зип и распаковывает его. Дистр станет больше? Ну... Вроде не так часто ставится/обновляется движок :)

**Comment by aliczin** [comment]
@nixel2007 возможно их будет 8 (восемь) - под каждую операционную систему с runtime и без runtime

**Comment by nixel2007** [comment]
И овм не перестанет работать, он поставляется в виде exe. Максимум - он больше не будет требовать дотнет фреймворка, так как будет идти вместе с рантаймом.
Над размером рантайма, думаю, можно будет поработать, а ля java modules system/jigsaw

**Comment by nixel2007** [comment]
@aliczin хм. А те, что без рантайма - их тоже будет несколько? Я думал, что отличаться будут только рантайм сборки, а без рантайма так и будет одна.

**Comment by aliczin** [comment]
@nixel2007 тут 2 момент которые светят при переходе на net.core

* дистрибьюция самого ovm - как будет работать компиляция в отдельный exe в новых условиях я так понимаю еще пне проверялось
* скачивание дистрибутивов под net.core - видимо придется определять операционку и уже под нее скачивать zip

ишуз же сами просили создавать - вот этот как раз и про это.

**Comment by nixel2007** [comment]
Ну, скачивать нужный дистр не проблема, благо и инструкции препроцессору появились и всегда остаётся "системная информация".
Дистрибьюция овм... Возможно на гитхабе появится не один экзешник, а несколько. Тоже не вижу большой проблемы
